---
title: "Effort Displacement Overview"
author: 
  - Min-Yang Lee^[NEFSC, Min-Yang.Lee@noaa.gov]
  - Greg Ardini^[NEFSC, Gregory.Ardini@noaa.gov]
  - Marina Chaji^[NEFSC, Marina.Chaji@noaa.gov]
  - Melanie Harsch^[AFSC Melanie.Harsch@noaa.gov]
  - Alan Haynie^[AFSC, Alan.Haynie@noaa.gov]
  - Bryce McManus^[AFSC, Bryce.McManus@noaa.gov]
  - Tammy Murphy^[NEFSC, Tammy.Murphy@noaa.gov]
  - Lisa Pfeiffer^[NWFSC, Lisa.Pfeiffer@noaa.gov]
  - Eric Thunberg^[NMFS OS&T, Eric.Thunberg@noaa.gov]

date: "`r format(Sys.time(), '%B %d, %Y, %H:%M')`"
output:
  pdf_document: default
  html_document:
    number_sections: yes
---




```{r setup, include=TRUE, echo=TRUE, results=FALSE}
# Project setup
# Load packages. Install if necessary.

# Set Path
here::i_am("effort_displacement_overview.Rmd")

# Load packages. I have purposefully loaded only a 'skinny' selection of packages.  
PKG <- c("here","leaflet", "tidyverse", "sf", "dbplyr")

for (p in PKG) {
  if(!require(p,character.only = TRUE)) {
    install.packages(p)
    require(p,character.only = TRUE)}
}

# Set or reset the data vintage string
# You might need to manually set the vintage_string
vintage_string<-Sys.Date()
vintage_string<-gsub("-","_",vintage_string)
vintage_string<-"2022_02_14"

#####################################################################################################
#
# If we are going to use "the data" (generated by data_extraction_and_processing_code.Rmd) to do anything, we should # NOT be extracting any data here.  If we need to make summary statistics or images, they should be constructed from # the output of "data_extraction_and_processing_code.Rmd"
# 
# Anyone who has put the output of the data processing code in their data/main folder should be able to build this 
# document. 
#####################################################################################################
# Load in the data.  

final_product_savename<-paste0("final_product_",vintage_string,".Rds")
# final_product<-readRDS(final_product, file=here("data","main",final_product_savename))
```



# Research Question and Motivation

## Plain English

How will wind energy development affect the Limited Access Scallop Fishery?  Where will firms choose to fish when areas are closed?  Will firms fish less? How much worse off with firms be?

## Economic Jargon

What are the annual changes in profits (or producer surplus) when a single wind area is closed? When many are closed?  If all are closed?  

# Empirical Setting

## Scallop Fishery

We are modeling the location choices of fishing vessels in the Limited Access Days-at-Sea scallop fishery. There are approximately 300-330 of these fishing vessels.  They are allocated "Open Area Days-at-Sea" and a quantity of trips and/or pounds into the "Access Areas."  They catch approximately 95% of the scallops.  The Limited Access DAS fleet can be further subdivided into Full-Time, Part-Time, and Occasional Fleets.  Vessels primarily use the New Bedford scallop dredge, but a few use a smaller dredge or a bottom trawl.  Over the 13 years in our dataset, there are approximately 40,000 trips taken by this fleet, split roughly evenly into "Open areas" and "Access Areas."

For Fishing Year 2016 and earlier, the fishing year Ran from March 1 to Feb 28/29. For fishing year 2017, the year ran from March 1 to March 31.  For 2018 and later, the fishing year runs from April 1 to March 31.

## Wind Energy

Here is a short description of the wind energy areas and how they will close (or not close) area to fishing.  18 wind areas currently under dev.  But many more are likely.

How close will fishing be able to occur within Wind Lease Areas / Turbines?  

The wind energy areas do not match the ten minute squares; we are currently planning on simulating the effects of closing a wind energy area by closing an entire ten minute square that is inside or touching a WEA.  

The buried cable route from a WEA to shore is likely to be closed as well.  Cable buried at shallow depths and marked with concrete.

# Data

Further detail about our data can be found [here](data_extraction_and_processing_code.Rmd).

# Methods